substitutions:
  device_name: sprinkler-controller
  friendly_name: "Sprinkler Controller"
  version: "2.0.2"

packages:
  sprinkler_controller: !include ESP_sprinkler-controller/package.yaml

# Optional local overrides:
# wifi:
#   manual_ip: !include ESP_sprinkler-controller/network_static_ip.local.yaml
