# ================================================================
#                                                          
#                 RUNTIME TRACKING                       
#                                                          
# ================================================================
# Saved as: config/package_sources/espyrain_for_home_assistant/sensors/sensors_espyrain_runtime_tracker.yaml

# ================================================================
# Today's history stats
# ================================================================
- platform: history_stats
  name: S1 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_1_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S2 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_2_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S3 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_3_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S4 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_4_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S5 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_5_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S6 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_6_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S7 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_7_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S8 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_8_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S9 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_9_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S10 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_10_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S11 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_11_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S12 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_12_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S13 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_13_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S14 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_14_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S15 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_15_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S16 Runtime Today
  entity_id: binary_sensor.espyrain_controller_station_16_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') }}"
  end: "{{ now() }}"

# ================================================================
# Yesterday's history stats
# ================================================================
- platform: history_stats
  name: S1 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_1_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S2 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_2_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S3 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_3_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S4 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_4_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S5 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_5_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S6 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_6_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S7 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_7_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S8 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_8_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S9 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_9_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S10 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_10_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S11 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_11_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S12 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_12_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S13 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_13_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S14 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_14_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S15 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_15_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

- platform: history_stats
  name: S16 Runtime Yesterday
  entity_id: binary_sensor.espyrain_controller_station_16_watering
  state: "on"
  type: time
  start: "{{ today_at('00:00') - timedelta(days=1) }}"
  end: "{{ today_at('00:00') }}"

# ================================================================
# This week's history stats
# ================================================================
- platform: history_stats
  name: S1 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_1_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S2 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_2_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S3 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_3_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S4 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_4_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S5 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_5_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S6 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_6_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S7 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_7_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S8 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_8_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S9 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_9_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S10 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_10_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S11 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_11_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S12 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_12_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S13 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_13_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S14 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_14_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S15 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_15_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "{{ now() }}"

- platform: history_stats
  name: S16 Runtime This Week
  entity_id: binary_sensor.espyrain_controller_station_16_watering
  state: "on"
  type: time
  start: "{{ as_timestamp(now().replace(hour=0, minute=0, second=0)) - now().weekday() * 86400 }}"
  end: "