############################################################
#                                                          #
#              SPRINKLER SCHEDULE TIMES                    #
#                   8 Schedules Total                      #
#                                                          #
############################################################
# # Schedule 1
sprinkler_schedule_1_time:
  name: "Schedule 1 Time"
  has_date: false
  has_time: true
  icon: mdi:clock-outline

# Schedule 2
sprinkler_schedule_2_time:
  name: "Schedule 2 Time"
  has_date: false
  has_time: true
  icon: mdi:clock-outline

# Schedule 3
sprinkler_schedule_3_time:
  name: "Schedule 3 Time"
  has_date: false
  has_time: true
  icon: mdi:clock-outline

# Schedule 4
sprinkler_schedule_4_time:
  name: "Schedule 4 Time"
  has_date: false
  has_time: true
  icon: mdi:clock-outline

# Schedule 5
sprinkler_schedule_5_time:
  name: "Schedule 5 Time"
  has_date: false
  has_time: true
  icon: mdi:clock-outline

# Schedule 6
sprinkler_schedule_6_time:
  name: "Schedule 6 Time"
  has_date: false
  has_time: true
  icon: mdi:clock-outline

# Schedule 7
sprinkler_schedule_7_time:
  name: "Schedule 7 Time"
  has_date: false
  has_time: true
  icon: mdi:clock-outline

# Schedule 8
sprinkler_schedule_8_time:
  name: "Schedule 8 Time"
  has_date: false
  has_time: true
  icon: mdi:clock-outline

sprinkler_manual_runtime:
  name: "Manual Runtime"
  has_date: false
  has_time: true
     
rain_delay_date:
  name: "Rain Delay Until"
  has_date: true
  has_time: false
  icon: mdi:weather-rainy
   
# Add to input_datetime.yaml
sprinkler_winter_mode_since:
  name: "Winter Mode Since"
  has_date: true
  has_time: false

sprinkler_winter_start:
  name: "Winter Start"
  has_date: true
  has_time: false
  icon: mdi:calendar-start

sprinkler_winter_end:
  name: "Winter End"
  has_date: true
  has_time: false
  icon: mdi:calendar-end


